services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: full-stack-webrtc
    ports:
      - 6969:6969
    volumes:
      - ./:/full-stack-webrtc
    environment:
      APP_PORT: 6969
      DB_HOST: db
      DB_PORT: 27017
      JWT_ACCESS_SECRET: abc
      JWT_PASSWORD_RESET_SECRET: def
      JWT_REFRESH_SECRET: hij
      SALT_ROUNDS: 6
      SENDGRID_API_KEY: SG.123
    depends_on:
      - db
  db:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db

volumes:
  db-volume: